[package]
name = "ruxn"
version = "0.1.0"
authors = ["Morgan Arnold <morgan.arnold@proton.me>"]
edition = "2021"
description = "An implementation of the Uxn virtual machine written in Rust."
repository = "https://github.com/CrashAndSideburns/ruxn"
license = "Unlicense"

[dependencies]
